name: Publish Nuget package

on:
  push:    
    branches-ignore:
      - '**'
    tags:
      - 'nuget-v*.*.*'

jobs:
  build:    
    runs-on: ubuntu-latest
    
    steps:    
    - uses: actions/checkout@v2
    
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: Fluidem.Core/Fluidem.Core.csproj
        # NuGet package id, used for version detection & defaults to project name
        # PACKAGE_NAME: # optional
        VERSION_FILE_PATH: Directory.Build.props
        NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}
        NUGET_SOURCE: https://nuget.pkg.github.com
        # Regex pattern to extract version info in a capturing group
        #VERSION_REGEX: # optional, default is ^\s*<Version>(.*)<\/Version>\s*$
        # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
        #VERSION_STATIC: # optional
        # Flag to toggle git tagging, enabled by default
        #TAG_COMMIT: # optional, default is true
        # Format of the git tag, [*] gets replaced with actual version
        # TAG_FORMAT: # optional, default is v*                
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        # INCLUDE_SYMBOLS: # optional
